services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - tg-network

  flow-service:
    build:
      context: .
      dockerfile: services/flow/Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${FLOW_SERVICE_PORT_INTERNAL}
    ports:
      - "${FLOW_SERVICE_PORT_EXTERNAL}:${FLOW_SERVICE_PORT_INTERNAL}"
    networks:
      - tg-network

  codegen-service:
    build:
      context: .
      dockerfile: services/codegen/Dockerfile
    depends_on:
      - flow-service
    environment:
      PORT: ${CODEGEN_SERVICE_PORT_INTERNAL}
    ports:
      - "${CODEGEN_SERVICE_PORT_EXTERNAL}:${CODEGEN_SERVICE_PORT_INTERNAL}"
    networks:
      - tg-network

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    depends_on:
      - flow-service
      - codegen-service
    environment:
      FLOW_HOST: ${FLOW_HOST}
      FLOW_PORT: ${FLOW_PORT}
      CODEGEN_HOST: ${CODEGEN_HOST}
      CODEGEN_PORT: ${CODEGEN_PORT}
      GATEWAY_PORT: ${GATEWAY_PORT_INTERNAL}
    ports:
      - "${GATEWAY_PORT_EXTERNAL}:${GATEWAY_PORT_INTERNAL}"
    networks:
      - tg-network

volumes:
  pgdata:

networks:
  tg-network:
    driver: bridge
